language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services: mysql

before_script:
  - mysql -e 'create database app_test;'
  - mysql app_test < src/Hope/RestBundle/Resources/tests/api_test_2014-08-04.sql.gz
  - composer install -n

script: phpunit -c app
