parameters:
#    hope_rest.example.class: Hope\RestBundle\Example

services:
#    hope_rest.example:
#        class: %hope_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
