parameters:
    hope_rest.home.service.class: Hope\RestBundle\Service\HomeService

services:
    hope.home.service:
        class: %hope_rest.home.service.class%
        arguments: ["@doctrine.orm.entity_manager"]
